# Prometheus监控配置
# 智能问答系统 v3.0 - 监控指标收集

global:
  # 数据抓取间隔
  scrape_interval: 15s
  # 规则评估间隔
  evaluation_interval: 15s
  # 外部标签
  external_labels:
    monitor: 'qa-system-monitor'
    datacenter: 'local'

# 规则文件
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 监控目标配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 30s

  # FastAPI应用监控
  - job_name: 'qa-system-app'
    static_configs:
      - targets: 
        - 'app:8000'
        - 'app-replica:8000'  # 如果有副本实例
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # PostgreSQL监控 (需要postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  # Redis监控 (需要redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # 节点监控 (需要node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker容器监控 (需要cadvisor)
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # 应用健康检查
  - job_name: 'health-check'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /health
    scrape_interval: 60s
    scrape_timeout: 10s

  # 自定义业务指标
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:8000']
    metrics_path: /api/v1/metrics/business
    scrape_interval: 60s
    basic_auth:
      username: 'prometheus'
      password: 'prometheus-password'

# 远程写入配置（可选，用于长期存储）
# remote_write:
#   - url: "http://remote-storage:9090/api/v1/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-storage:9090/api/v1/read" 